
version: "3.8"

services:
  pitchlake_websocket:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     APP_URL: ${APP_URL}
     DB_URL: ${DB_URL}
    ports:
      - "6060:6060" # Adjust this port if needed
